### ISSUE TITLE
Examples ?

### ISSUE THREAD

**Issue by donsenilo1968** [pauldeng/arduino-leonardo-eth-w5500-powerdown-example#1]
Hi

Where are the mentioned Examples ?

**Comment by pauldeng** [comment]
The repo itself is the example.

It is a PlantfomIO project you can import and the source code is well documented in https://github.com/pauldeng/arduino-leonardo-eth-w5500-powerdown-example/blob/c6ff2e4dba2eb8a9cfc1a1ca22dee6145db9abbb/src/main.cpp.

Cheers,
Paul
